config/routes.rb
Rails.application.routes.draw do
  
  
  
  # 顧客側画面・処理のルーティング
  devise_for :members, controllers: {
    sessions: 'customer/sessions',
    passwords: 'customer/passwords',
    registrations: 'customer/registrations',
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/shop' => 'homes#shop'

    get '/pizzas/search' => 'pizzas#search'   # ピザ一覧画面での検索後に表示する、検索結果表示画面
    post '/pizzas/search' => 'pizzas#search'  # ransackによる、ピザ一覧画面での検索処理
    resources :pizzas, only: [:index, :show]

    get '/members/confirm' => 'members#confirm'           # 顧客の退会確認画面
    patch '/members/withdrawal' => 'members#withdrawal'   # 顧客の退会処理(会員ステータスの更新)
    resources :members, only: [:show, :edit, :update]

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all' # カート内商品の全削除
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/confirm' => 'orders#confirm'       # 注文情報確認画面
    post '/orders/confirm' => 'orders#confirm'      # 注文情報確認画面の裏処理
    get '/orders/complete' => 'orders#complete'     # 注文完了画面
    resources :orders, only: [:index, :new, :create, :show]

    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  # <------------------------------------------>

  # 管理者側画面・処理のルーティング
  devise_for :admins, path: 'admin',
                      controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords',
                        registrations: 'admin/registrations',
                      }

  namespace :admin do
    root to: 'homes#top'
    get '/admin' => 'homes#top'
    resources :pizzas
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_pizzas, only: [:update]
  end
  # <------------------------------------------>
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_pizzas, dependent: :destroy
  
  attachment :image

  validates :pizza_name, :price, :pizza_size, :sales_status, presence: true

  # enumによるピザのサイズ、販売ステータスの管理
  enum sales_status: { 販売中: 0, 販売停止中: 1 }
  enum pizza_size: { small（直径23cm）: 0, medium（直径28cm）: 1, large（直径33cm）: 2 }
end

app/controllers/admin/pizzas_controller.rb
class Admin::PizzasController < ApplicationController
  before_action :authenticate_admin!

  def index
    @pizzas = Pizza.page(params[:page]).per(9).order(created_at: :desc)
  end

  def new
    @pizza = Pizza.new
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      flash[:success] = "商品データを保存しました！"
      redirect_to admin_pizzas_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :new
    end
  end

  def show
    @pizza = Pizza.find(params[:id])
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def update
    @pizza = Pizza.find(params[:id])
    if @pizza.update(pizza_params)
      flash[:success] = "編集内容を保存しました！"
      redirect_to admin_pizza_path(@pizza)
    else
      flash[:danger] = "編集内容に誤りがあります！"
      redirect_to edit_admin_pizza_path(@pizza)
    end
  end

  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy
    flash[:success] = "選択した商品データを削除しました！"
    redirect_to admin_pizzas_path
  end

  # ピザ商品データのストロングパラメータ設定
  private

  def pizza_params
    params.require(:pizza).permit(:image, :pizza_name, :price, :pizza_size, :sales_status)
  end
end

app/controllers/customer/pizzas_controller.rb
class Customer::PizzasController < ApplicationController
  before_action :search_pizza, only: [:index, :search]

  def index
    @pizzas = Pizza.page(params[:page]).per(6).order(created_at: :desc)
  end

  def search
    @results = @search.result.page(params[:page]).per(6)
  end

  def show
    @pizza = Pizza.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  # 検索オブジェクトの生成
  def search_pizza
    @search = Pizza.ransack(params[:q])
  end
end

app/helpers/admin/pizzas_helper.rb
module Admin::PizzasHelper
end

app/helpers/customer/pizzas_helper.rb
module Customer::PizzasHelper
end

app/views/admin/pizzas/edit.html.erb
<div class="container my-5">
  <div class="row mb-4">
    <h1><strong>ピザ詳細情報編集</strong></h1>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @pizza, url: admin_pizza_path, method: :patch, local: true do |f| %>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">商品名</label>
          <div class="col-sm-9">
            <%= f.text_field :pizza_name, class: 'form-control', placeholder: "商品名" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">商品画像</label>
          <div class="col-sm-9">
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">税抜価格</label>
          <div class="col-sm-8">
            <%= f.text_field :price, class: 'form-control', placeholder: "税抜価格" %>
          </div>
          <div class="col-sm-1">円</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3">サイズ</label>
          <div class="col-sm-9">
            <%= f.select :pizza_size, Pizza.pizza_sizes.keys, include_blank: "--選択してください--", class: 'form-control', required: true %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col">販売ステータス</label>
          <div class="col">
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :sales_status, :販売中, class: "form-check-input" %>販売中
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :sales_status, :販売停止中, class: "form-check-input" %>販売停止中
              </label>
            </div>
          </div>
        </div>
        <div class="form-group text-center">
          <%=f.submit "新規登録", class: "btn btn-lg btn-success " %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/pizzas/index.html.erb
<div class="container my-5">
  <div class="row mb-4">
    <h1 class="col"><strong>ピザ一覧</strong></h1>
    <%= link_to new_admin_pizza_path do %>
      <span class="fas fa-pizza-slice fa-3x"></span>
      ピザ新規登録はこちらから
    <% end %>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>ピザID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>サイズ</th>
            <th>販売ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @pizzas.each do |pizza| %>
            <tr>
              <td>
                <%= pizza.id %>
              </td>
              <td>
                <%= link_to admin_pizza_path(pizza) do %>
                  <%= pizza.pizza_name %>
                <% end %>
              </td>
              <td>
                <%= (pizza.price).to_s(:delimited) %>円
              </td>
              <td>
                <%= pizza.pizza_size %>
              </td>
              <td>
                <%= pizza.sales_status %>
              </td>
              <td>
                <%= link_to "削除", admin_pizza_path(pizza), method: :delete, class: "btn btn-sm btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @pizzas %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pizzas/new.html.erb
<div class="container my-5">
  <div class="row mb-4">
    <h1><strong>ピザ新規登録</strong></h1>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @pizza, url: admin_pizzas_path, local: true do |f| %>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">商品名</label>
          <div class="col-sm-9">
            <%= f.text_field :pizza_name, class: 'form-control', placeholder: "商品名" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">商品画像</label>
          <div class="col-sm-9">
            <%= f.attachment_field :image %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-form-label col-sm-3">税抜価格</label>
          <div class="col-sm-8">
            <%= f.text_field :price, class: 'form-control', placeholder: "税抜価格" %>
          </div>
          <div class="col-sm-1">円</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3">サイズ</label>
          <div class="col-sm-9">
            <%= f.select :pizza_size, Pizza.pizza_sizes.keys, include_blank: "--選択してください--", class: 'form-control', required: true %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col">販売ステータス</label>
          <div class="col">
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :sales_status, :販売中, class: "form-check-input" %>販売中
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :sales_status, :販売停止中, class: "form-check-input" %>販売停止中
              </label>
            </div>
          </div>
        </div>
        <div class="form-group text-center">
          <%=f.submit "新規登録", class: "btn btn-lg btn-success " %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/pizzas/show.html.erb
<div class="container my-5">
  <h1><strong>ピザ詳細情報</strong></h1>
  <div class="row mt-5">
    <div class="col-md-6">
      <table class="table table-bordered table-hover">
        <tbody>
          <tr>
            <td class="table-dark">商品名</td>
            <td><%= @pizza.pizza_name %></td>
          </tr>
          <tr>
            <td class="table-dark">税抜価格</td>
            <td><%= (@pizza.price).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td class="table-dark">サイズ</td>
            <td><%= @pizza.pizza_size %></td>
          </tr>
          <tr>
            <td class="table-dark">販売ステータス</td>
            <td><%= @pizza.sales_status %></td>
          </tr>
        </tbody>
      </table>
      
      
      <div class="row mt-5 justify-content-center">
        <%= link_to edit_admin_pizza_path(@pizza) do %>
          <span class="btn btn-outline-info">ピザ詳細情報を編集する</span>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <%= attachment_image_tag @pizza, :image, :fill, 500, 500, class: "img-fluid mx-auto" %>
    </div>
  </div>
</div>