config/routes.rb
Rails.application.routes.draw do
  
  
  
  # 顧客側画面・処理のルーティング
  devise_for :members, controllers: {
    sessions: 'customer/sessions',
    passwords: 'customer/passwords',
    registrations: 'customer/registrations',
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/shop' => 'homes#shop'

    get '/pizzas/search' => 'pizzas#search'   # ピザ一覧画面での検索後に表示する、検索結果表示画面
    post '/pizzas/search' => 'pizzas#search'  # ransackによる、ピザ一覧画面での検索処理
    resources :pizzas, only: [:index, :show]

    get '/members/confirm' => 'members#confirm'           # 顧客の退会確認画面
    patch '/members/withdrawal' => 'members#withdrawal'   # 顧客の退会処理(会員ステータスの更新)
    resources :members, only: [:show, :edit, :update]

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all' # カート内商品の全削除
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/confirm' => 'orders#confirm'       # 注文情報確認画面
    post '/orders/confirm' => 'orders#confirm'      # 注文情報確認画面の裏処理
    get '/orders/complete' => 'orders#complete'     # 注文完了画面
    resources :orders, only: [:index, :new, :create, :show]

    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  # <------------------------------------------>

  # 管理者側画面・処理のルーティング
  devise_for :admins, path: 'admin',
                      controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords',
                        registrations: 'admin/registrations',
                      }

  namespace :admin do
    root to: 'homes#top'
    get '/admin' => 'homes#top'
    resources :pizzas
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_pizzas, only: [:update]
  end
  # <------------------------------------------>
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_pizzas, dependent: :destroy
  
  attachment :image

  validates :pizza_name, :price, :pizza_size, :sales_status, presence: true

  # enumによるピザのサイズ、販売ステータスの管理
  enum sales_status: { 販売中: 0, 販売停止中: 1 }
  enum pizza_size: { small（直径23cm）: 0, medium（直径28cm）: 1, large（直径33cm）: 2 }
end

app/controllers/admin/pizzas_controller.rb
class Admin::PizzasController < ApplicationController
  before_action :authenticate_admin!

  def index
    @pizzas = Pizza.page(params[:page]).per(9).order(created_at: :desc)
  end

  def new
    @pizza = Pizza.new
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      flash[:success] = "商品データを保存しました！"
      redirect_to admin_pizzas_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :new
    end
  end

  def show
    @pizza = Pizza.find(params[:id])
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def update
    @pizza = Pizza.find(params[:id])
    if @pizza.update(pizza_params)
      flash[:success] = "編集内容を保存しました！"
      redirect_to admin_pizza_path(@pizza)
    else
      flash[:danger] = "編集内容に誤りがあります！"
      redirect_to edit_admin_pizza_path(@pizza)
    end
  end

  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy
    flash[:success] = "選択した商品データを削除しました！"
    redirect_to admin_pizzas_path
  end

  # ピザ商品データのストロングパラメータ設定
  private

  def pizza_params
    params.require(:pizza).permit(:image, :pizza_name, :price, :pizza_size, :sales_status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_member!

  def create
    @cart_item = CartItem.new(cart_item_params_create)
    @cart_item.member_id = current_member.id
    @cart_item.pizza_id = params[:pizza_id]
    @cart_item.save
    flash[:success] = '選択したピザをカートに入れました！'
    redirect_to cart_items_path
  end

  def index
    @cart_items = current_member.cart_items
    @total_price = calculate(current_member)
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item = CartItem.update(cart_item_params_update)
    flash[:success] = "ピザの枚数を変更しました！"
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "選択したピザをカートから削除しました！"
    redirect_to cart_items_path
  end

  def destroy_all
    current_member.cart_items.destroy_all
    flash[:success] = 'カート内商品を全て削除しました！'
    redirect_to cart_items_path
  end

  # カート内データのストロングパラメータ
  private

  # create用のストロングパラメータ
  def cart_item_params_create
    params.require(:cart_item).permit(:number_of_sheets, :pizza_id, :member_id)
  end

  # update用のストロングパラメータ
  def cart_item_params_update
    params.permit(:number_of_sheets, :pizza_id, :member_id)
  end

  # ショッピングカート合計金額の算出
  def calculate(member)
    total_price = 0
    member.cart_items.each do |cart_item|
      total_price += cart_item.number_of_sheets.to_i * cart_item.pizza.price
    end
    (total_price * 1.1).floor
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/deliveries_controller.rb
class Customer::DeliveriesController < ApplicationController
  before_action :authenticate_member!

  def index
    @deliveries = Delivery.where(member_id: current_member.id)
  end

  def create
    @delivery = Delivery.new
    @delivery.member_id = current_member.id
    @delivery.name = params[:name]
    @delivery.postal_code = params[:postal_code]
    @delivery.address = params[:address]
    @delivery.telephone_number = params[:telephone_number]
    if @delivery.save
      flash[:success] = "新規配達先情報を登録しました！"
      redirect_to deliveries_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :index
    end
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    @delivery = Delivery.find(params[:id])
    if @delivery.update(delivery_params)
      flash[:success] = "配達先情報を編集しました！"
      redirect_to deliveries_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :edit
    end
  end

  def destroy
    @delivery = Delivery.find(params[:id])
    @delivery.destroy
    flash[:success] = "配達先情報を削除しました！"
    redirect_to deliveries_path
  end

  # 配達先情報のストロングパラメータ
  private

  def delivery_params
    params.permit(:name, :postal_code, :address, :telephone_number)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
  end

  def about
  end

  def shop
  end
end

app/controllers/customer/members_controller.rb
class Customer::MembersController < ApplicationController
  before_action :authenticate_member!

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(update_params)
      flash[:success] = "ユーザー情報を更新しました！"
      redirect_to member_path(current_member)
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :edit
    end
  end

  def confirm
  end

  # ユーザーの退会処理
  def withdrawal
    # withdrawal_statusをfalseにし、「退会」ステータスに変更する
    current_member.update(withdrawal_status: "退会")

    # ログアウトし、session内のデータをリセットする
    reset_session
    flash[:success] = "退会処理が完了しました。"
    redirect_to root_path
  end

  # ユーザー情報のストロングパラメータ
  private

  def update_params
    params.require(:member).permit(:full_name, :full_name_kana, :email, :encrypted_password)
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_member!

  # 注文情報入力画面
  def new
    @order = Order.new
    @deliveries = Delivery.where(member_id: current_member.id)
  end

  # 注文情報入力画面で入力した内容をsessionで一時保存
  def confirm
    @order = current_member.orders
    @total_price = calculate(current_member)

    session[:payment_method] = params[:payment_method]

    # 「本サイトのご利用が初めての方」を選択した場合の処理
    if params[:delivery] == "new_address"
      session[:postal_code] = params[:session][:postal_code]
      session[:address] = params[:session][:address]
      session[:name] = params[:session][:name]
      session[:telephone_number] = params[:session][:telephone_number]

    # 「マイページにて配達先の登録が完了している方」を選択した場合の処理
    elsif params[:delivery] == "my_address"
      session[:postal_code] =  params[:session][:delivery_postal_code]
      session[:address] = params[:session][:delivery_address]
      session[:name] = params[:session][:delivery_name]
      session[:telephone_number] = params[:session][:delivery_telephone_number]
    end

    # 郵便番号、住所、宛名、電話番号のいずれかが入力されていない場合の処理
    if session[:postal_code] == ""
      flash[:danger] = "郵便番号を入力してください！"
      redirect_to new_order_path
    elsif session[:address] == ""
      flash[:danger] = "配達先住所を入力してください！"
      redirect_to new_order_path
    elsif session[:name] == ""
      flash[:danger] = "宛名を入力してください！"
      redirect_to new_order_path
    elsif session[:telephone_number] == ""
      flash[:danger] = "電話番号を入力してください！"
      redirect_to new_order_path  
    end
    
  end

  def create
    # 注文情報の保存
    @order = Order.new
    @order.member_id = current_member.id
    @order.delivery_postal_code = session[:postal_code]
    @order.delivery_address = session[:address]
    @order.delivery_name = session[:name]
    @order.delivery_telephone_number = session[:telephone_number]
    @order.payment_method = session[:payment_method]
    @order.billing_amount = calculate(current_member)
    @order.order_status = 0
    @order.save

    # 注文商品ごとの詳細データの保存
    current_member.cart_items.each do |cart|
      @order_pizza = OrderPizza.new
      @order_pizza.order_id = @order.id
      @order_pizza.pizza_id = cart.pizza.id
      @order_pizza.price = cart.pizza.price
      @order_pizza.number_of_sheets = cart.number_of_sheets
      @order_pizza.cooking_status = 0
      @order_pizza.save
    end

    # 現在ユーザーのカート内データ、及び支払方法・お届け先データの削除
    current_member.cart_items.destroy_all
    session.delete(:payment_method)
    session.delete(:postal_code)
    session.delete(:address)
    session.delete(:name)
    session.delete(:telephone_number)
    flash[:success] = "注文が完了しました！"
    redirect_to orders_complete_path
  end

  # 注文完了画面
  def complete
  end

  def index
    @orders = Order.where(member_id: current_member.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
  end

  # 注文データのストロングパラメータ
  private

  def confirm_params
    params.permit(:payment_method, :postal_code, :address, :name, :telephone_number)
  end

  def calculate(member)
    total_price = 0
    member.cart_items.each do |cart_item|
      total_price += cart_item.number_of_sheets * cart_item.pizza.price
    end
    (total_price * 1.1).floor
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/pizzas_controller.rb
class Customer::PizzasController < ApplicationController
  before_action :search_pizza, only: [:index, :search]

  def index
    @pizzas = Pizza.page(params[:page]).per(6).order(created_at: :desc)
  end

  def search
    @results = @search.result.page(params[:page]).per(6)
  end

  def show
    @pizza = Pizza.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  # 検索オブジェクトの生成
  def search_pizza
    @search = Pizza.ransack(params[:q])
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_after_withdrawal_member, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_after_withdrawal_member
    @member = Member.find_by(email: params[:member][:email])
    if @member
      if @member.valid_password?(params[:member][:password]) && @member.withdrawal_status == "退会"
        flash[:danger] = "すでに退会しています。"
        redirect_to new_member_session_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/pizzas_helper.rb
module Admin::PizzasHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/deliveries_helper.rb
module Customer::DeliveriesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/members_helper.rb
module Customer::MembersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/pizzas/index.html.erb
<div class="pizza-index img-fluid">
  <div class="container text-center py-5">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto menu-background p-3">
        <h1><strong>ピザメニュー</strong></h1>
        <p class="lead">
          Aboutページで紹介したピザの一覧です。<br>
          会員登録後であれば、ピザの注文が可能です！
        </p>
        <% unless member_signed_in? %>
          <p>
            <a href="/members/sign_up" class="btn btn-primary my-2">会員登録する</a>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="p-5">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-5 mx-auto">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title text-center my-3">ピザを検索する</h3>
            <%= search_form_for @search, url: pizzas_search_path, method: :post do |f| %>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-text"><i class="fas fa-search"></i></span>
                  <%= f.search_field :pizza_name_cont, class: "form-control", placeholder: "キーワード" %>
                </div>
              </div>
              <div class="form-group mt-4">
                <%= f.submit "検索", class: "btn btn-outline-success form-control" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
      <% @pizzas.each do |pizza| %>
        <div class="col py-3">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top img-fluid" width="100%" height="0" xmlns="http://www.w3.org/2000/svg" preserveAspecRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap">
              <%= attachment_image_tag pizza, :image, format: 'jpg', style: "height: 200px;" %>
            </svg>
            <div class="card-body">
              <div class="card-text">
                <div class="row">
                  <strong>商品名 : 
                    <%= link_to pizza_path(pizza) do %>
                      <%= pizza.pizza_name %>
                    <% end %>  
                  </strong>
                </div>
                <div class="row my-1">
                  <strong>販売サイズ : <%= pizza.pizza_size %></strong>
                </div>
                <div class="row">
                  <strong>税込金額 : <%= ((pizza.price)*1.1).floor.to_s(:delimited) %> 円</strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @pizzas %>
    </div>
  </div>
</div>

app/views/customer/pizzas/search.html.erb
<div class="py-5">
  <div class="container">
    <h1><strong>検索結果</strong></h1>
    <h2>検索ワードに該当する件数 : <%= @results.count %>件</h2>
    <% if @results.count == 0 %>
      <h3 class="text-center">該当するピザはありませんでした。</h3>
      <div class="row d-flex justify-content-center">
        <%= link_to "ピザ一覧へ戻る", pizzas_path, class: "btn btn-outline-info" %>
      </div>
    <% end %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @results.each do |pizza| %>
        <div class="col my-3">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top img-fluid" width="100%" height="0" xmlns="http://www.w3.org/2000/svg" preserveAspecRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap">
              <%= attachment_image_tag pizza, :image, :fill, 400, 300 %>
            </svg>
            <div class="card-body">
              <div class="card-text">
                <div class="row">
                  <strong>商品名 : 
                    <%= link_to pizza_path(pizza) do %>
                      <%= pizza.pizza_name %>
                    <% end %>  
                  </strong>
                </div>
                <div class="row my-1">
                  <strong>販売サイズ : <%= pizza.pizza_size %></strong>
                </div>
                <div class="row">
                  <strong>税込金額 : <%= ((pizza.price)*1.1).floor.to_s(:delimited) %> 円</strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= paginate @results %>
    </div>
  </div>
</div>

app/views/customer/pizzas/show.html.erb
<div class="container my-5">
  <div class="card col-lg-6 col-sm-8 mx-auto">
    <%= form_with model: @cart_item, url: cart_items_path(pizza_id: @pizza), method: :post, local: true do |f| %>
    <div class="text-center"> 
      <svg class="bd-placeholder-img card-img-top img-fluid" width="100%" height="0" xmlns="http://www.w3.org/2000/svg" preserveAspecRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap">
        <%= attachment_image_tag @pizza, :image, format: 'jpg', size: "400x300" %>
      </svg>
    </div>
    <div class="card-body">
      <h4 class="card-title text-center">
        商品名 : <%= @pizza.pizza_name %>
      </h4>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        販売サイズ : <%= @pizza.pizza_size %>
      </li>
      <li class="list-group-item">
        税込価格 : <%= (@pizza.price * 1.1).floor.to_s(:delimited) %> 円
      </li>
      <div class="d-flex justify-content-between align-items-center p-3">
        <div class="btn-group">
          <%= link_to "ピザメニューへ戻る", pizzas_path, class: "btn btn-sm btn-outline-secondary" %>
        </div>
        <% if member_signed_in? %>
          <div class="btn-group">
            <%= f.select :number_of_sheets, [*1..5], class: "form-control" %><span class="d-flex align-items-center mx-1">枚を</span>
            <button type="submit" class="btn-sm btn-outline-success">
              <i class="fas fa-shopping-cart"></i> カートに入れる
            </button>
          </div>
        <% end %>
      </div>
    </ul>
  <% end %>  
  </div>
</div>