config/routes.rb
Rails.application.routes.draw do
  
  
  
  # 顧客側画面・処理のルーティング
  devise_for :members, controllers: {
    sessions: 'customer/sessions',
    passwords: 'customer/passwords',
    registrations: 'customer/registrations',
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/shop' => 'homes#shop'

    get '/pizzas/search' => 'pizzas#search'   # ピザ一覧画面での検索後に表示する、検索結果表示画面
    post '/pizzas/search' => 'pizzas#search'  # ransackによる、ピザ一覧画面での検索処理
    resources :pizzas, only: [:index, :show]

    get '/members/confirm' => 'members#confirm'           # 顧客の退会確認画面
    patch '/members/withdrawal' => 'members#withdrawal'   # 顧客の退会処理(会員ステータスの更新)
    resources :members, only: [:show, :edit, :update]

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all' # カート内商品の全削除
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/confirm' => 'orders#confirm'       # 注文情報確認画面
    post '/orders/confirm' => 'orders#confirm'      # 注文情報確認画面の裏処理
    get '/orders/complete' => 'orders#complete'     # 注文完了画面
    resources :orders, only: [:index, :new, :create, :show]

    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  # <------------------------------------------>

  # 管理者側画面・処理のルーティング
  devise_for :admins, path: 'admin',
                      controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords',
                        registrations: 'admin/registrations',
                      }

  namespace :admin do
    root to: 'homes#top'
    get '/admin' => 'homes#top'
    resources :pizzas
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_pizzas, only: [:update]
  end
  # <------------------------------------------>
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_pizzas
  belongs_to :member

  validates :member_id, :delivery_postal_code, :delivery_address, :delivery_name, :delivery_telephone_number, :billing_amount, :payment_method, presence: true
  validates :delivery_telephone_number, length: { minimum: 10 }
  # enumによる支払方法、注文ステータスの管理
  enum payment_method: { 現金: 0, クレジットカード: 1, 銀行振込: 2 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 配達準備中: 2, 配達準備完了: 3, 配達中: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
  end

  def update
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
    @order.update(order_params)

    # 注文ステータスを「入金確認」にすると、調理ステータスが「調理中」に更新される処理
    if @order.order_status == "入金確認"
      @order_pizzas.update_all(cooking_status: "調理中")
      flash[:success] = "注文ステータスを「入金確認」に、調理ステータスを「調理中」に変更しました！"
      redirect_to admin_order_path(@order)
    # 注文ステータスを「入金待ち」にすると、調理ステータスが「調理不可」に更新される処理
    elsif @order.order_status == "入金待ち"
      @order_pizzas.update_all(cooking_status: "調理不可")
      flash[:success] = "注文ステータスを「入金待ち」に、調理ステータスを「調理不可」に変更しました！"
      redirect_to admin_order_path(@order)
    # 注文ステータスを上記の2項目以外にした場合
    else
      flash[:success] = "注文ステータスを更新しました！"
      redirect_to admin_order_path(@order)
    end
  end

  # 注文データのストロングパラメータ設定
  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_member!

  def create
    @cart_item = CartItem.new(cart_item_params_create)
    @cart_item.member_id = current_member.id
    @cart_item.pizza_id = params[:pizza_id]
    @cart_item.save
    flash[:success] = '選択したピザをカートに入れました！'
    redirect_to cart_items_path
  end

  def index
    @cart_items = current_member.cart_items
    @total_price = calculate(current_member)
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item = CartItem.update(cart_item_params_update)
    flash[:success] = "ピザの枚数を変更しました！"
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "選択したピザをカートから削除しました！"
    redirect_to cart_items_path
  end

  def destroy_all
    current_member.cart_items.destroy_all
    flash[:success] = 'カート内商品を全て削除しました！'
    redirect_to cart_items_path
  end

  # カート内データのストロングパラメータ
  private

  # create用のストロングパラメータ
  def cart_item_params_create
    params.require(:cart_item).permit(:number_of_sheets, :pizza_id, :member_id)
  end

  # update用のストロングパラメータ
  def cart_item_params_update
    params.permit(:number_of_sheets, :pizza_id, :member_id)
  end

  # ショッピングカート合計金額の算出
  def calculate(member)
    total_price = 0
    member.cart_items.each do |cart_item|
      total_price += cart_item.number_of_sheets.to_i * cart_item.pizza.price
    end
    (total_price * 1.1).floor
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/deliveries_controller.rb
class Customer::DeliveriesController < ApplicationController
  before_action :authenticate_member!

  def index
    @deliveries = Delivery.where(member_id: current_member.id)
  end

  def create
    @delivery = Delivery.new
    @delivery.member_id = current_member.id
    @delivery.name = params[:name]
    @delivery.postal_code = params[:postal_code]
    @delivery.address = params[:address]
    @delivery.telephone_number = params[:telephone_number]
    if @delivery.save
      flash[:success] = "新規配達先情報を登録しました！"
      redirect_to deliveries_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :index
    end
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    @delivery = Delivery.find(params[:id])
    if @delivery.update(delivery_params)
      flash[:success] = "配達先情報を編集しました！"
      redirect_to deliveries_path
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :edit
    end
  end

  def destroy
    @delivery = Delivery.find(params[:id])
    @delivery.destroy
    flash[:success] = "配達先情報を削除しました！"
    redirect_to deliveries_path
  end

  # 配達先情報のストロングパラメータ
  private

  def delivery_params
    params.permit(:name, :postal_code, :address, :telephone_number)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
  end

  def about
  end

  def shop
  end
end

app/controllers/customer/members_controller.rb
class Customer::MembersController < ApplicationController
  before_action :authenticate_member!

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(update_params)
      flash[:success] = "ユーザー情報を更新しました！"
      redirect_to member_path(current_member)
    else
      flash[:danger] = "記載内容に誤りがあります！"
      render :edit
    end
  end

  def confirm
  end

  # ユーザーの退会処理
  def withdrawal
    # withdrawal_statusをfalseにし、「退会」ステータスに変更する
    current_member.update(withdrawal_status: "退会")

    # ログアウトし、session内のデータをリセットする
    reset_session
    flash[:success] = "退会処理が完了しました。"
    redirect_to root_path
  end

  # ユーザー情報のストロングパラメータ
  private

  def update_params
    params.require(:member).permit(:full_name, :full_name_kana, :email, :encrypted_password)
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_member!

  # 注文情報入力画面
  def new
    @order = Order.new
    @deliveries = Delivery.where(member_id: current_member.id)
  end

  # 注文情報入力画面で入力した内容をsessionで一時保存
  def confirm
    @order = current_member.orders
    @total_price = calculate(current_member)

    session[:payment_method] = params[:payment_method]

    # 「本サイトのご利用が初めての方」を選択した場合の処理
    if params[:delivery] == "new_address"
      session[:postal_code] = params[:session][:postal_code]
      session[:address] = params[:session][:address]
      session[:name] = params[:session][:name]
      session[:telephone_number] = params[:session][:telephone_number]

    # 「マイページにて配達先の登録が完了している方」を選択した場合の処理
    elsif params[:delivery] == "my_address"
      session[:postal_code] =  params[:session][:delivery_postal_code]
      session[:address] = params[:session][:delivery_address]
      session[:name] = params[:session][:delivery_name]
      session[:telephone_number] = params[:session][:delivery_telephone_number]
    end

    # 郵便番号、住所、宛名、電話番号のいずれかが入力されていない場合の処理
    if session[:postal_code] == ""
      flash[:danger] = "郵便番号を入力してください！"
      redirect_to new_order_path
    elsif session[:address] == ""
      flash[:danger] = "配達先住所を入力してください！"
      redirect_to new_order_path
    elsif session[:name] == ""
      flash[:danger] = "宛名を入力してください！"
      redirect_to new_order_path
    elsif session[:telephone_number] == ""
      flash[:danger] = "電話番号を入力してください！"
      redirect_to new_order_path  
    end
    
  end

  def create
    # 注文情報の保存
    @order = Order.new
    @order.member_id = current_member.id
    @order.delivery_postal_code = session[:postal_code]
    @order.delivery_address = session[:address]
    @order.delivery_name = session[:name]
    @order.delivery_telephone_number = session[:telephone_number]
    @order.payment_method = session[:payment_method]
    @order.billing_amount = calculate(current_member)
    @order.order_status = 0
    @order.save

    # 注文商品ごとの詳細データの保存
    current_member.cart_items.each do |cart|
      @order_pizza = OrderPizza.new
      @order_pizza.order_id = @order.id
      @order_pizza.pizza_id = cart.pizza.id
      @order_pizza.price = cart.pizza.price
      @order_pizza.number_of_sheets = cart.number_of_sheets
      @order_pizza.cooking_status = 0
      @order_pizza.save
    end

    # 現在ユーザーのカート内データ、及び支払方法・お届け先データの削除
    current_member.cart_items.destroy_all
    session.delete(:payment_method)
    session.delete(:postal_code)
    session.delete(:address)
    session.delete(:name)
    session.delete(:telephone_number)
    flash[:success] = "注文が完了しました！"
    redirect_to orders_complete_path
  end

  # 注文完了画面
  def complete
  end

  def index
    @orders = Order.where(member_id: current_member.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
  end

  # 注文データのストロングパラメータ
  private

  def confirm_params
    params.permit(:payment_method, :postal_code, :address, :name, :telephone_number)
  end

  def calculate(member)
    total_price = 0
    member.cart_items.each do |cart_item|
      total_price += cart_item.number_of_sheets * cart_item.pizza.price
    end
    (total_price * 1.1).floor
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/pizzas_controller.rb
class Customer::PizzasController < ApplicationController
  before_action :search_pizza, only: [:index, :search]

  def index
    @pizzas = Pizza.page(params[:page]).per(6).order(created_at: :desc)
  end

  def search
    @results = @search.result.page(params[:page]).per(6)
  end

  def show
    @pizza = Pizza.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  # 検索オブジェクトの生成
  def search_pizza
    @search = Pizza.ransack(params[:q])
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_after_withdrawal_member, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_after_withdrawal_member
    @member = Member.find_by(email: params[:member][:email])
    if @member
      if @member.valid_password?(params[:member][:password]) && @member.withdrawal_status == "退会"
        flash[:danger] = "すでに退会しています。"
        redirect_to new_member_session_path
      end
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/deliveries_helper.rb
module Customer::DeliveriesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/members_helper.rb
module Customer::MembersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/orders/complete.html.erb
<div class="container my-5">
  <div class="text-center">
    <h1><strong>ご注文ありがとうございました！</strong></h1>
  </div>
  <div class="mt-4 text-center">
    <%= link_to "ピザメニューへ戻る", pizzas_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/customer/orders/confirm.html.erb
<div class="container mx-auto pt-5">
  <div class="col">
     <h1 class="text-center">
      <i class="fas fa-check-square fa-2x"></i>
      <strong>注文情報確認</strong>
    </h1>
  </div>
  <%= form_with scope: :session, model: @order, url: orders_path, method: :post, local: true do |f| %>
    <div class="row my-5 mx-auto">
      <div class="col-sm-8">
        <table class="table table-hover table-bordered">
          <thead class="thead-dark">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>枚数</th>
            <th>小計</th>
          </thead>
          <tbody>
          <% current_member.cart_items.each do |cart| %>
            <tr>
              <td>
                <%= cart.pizza.pizza_name %>
              </td>
              <td>
                <%= (cart.pizza.price * 1.1).floor.to_s(:delimited) %>
              </td>
              <td>
                <%= cart.number_of_sheets %>
              </td>
              <td>
                <%= ((cart.pizza.price * 1.1).floor*(cart.number_of_sheets)).to_s(:delimited) %>
              </td>
            </tr>
          <% end %>  
          </tbody>
        </table>
      </div>
      <div class="col-sm-3 ml-auto">
        <table class="table table-hover table-bordered">
          <thead class="table-danger">
            <tr>
              <th class="text-center"><strong>請求金額</strong></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-center">
                <strong><%= @total_price.to_s(:delimited) %>円</strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col my-5 mx-auto">
      <h2 class="col text-center mb-4"><strong>支払方法</strong></h2>
      <div class="row d-flex justify-content-center">
        <strong><%= session[:payment_method] %></strong>
      </div>
    </div>
    <div class="col my-5 mx-auto">
      <h2 class="col text-center mb-4"><strong>お届け先</strong></h2>
      <div class="col-sm-6 col-md-9 mx-auto">
        <table class="table table-borderless d-flex justify-content-center">
          <tr>
            <td>氏名</td>
            <td>
              <%= session[:name] %>
            </td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td>
              〒<%= session[:postal_code] %>
            </td>
          </tr>
          <tr>
            <td>住所</td>
            <td>
              <%= session[:address] %>
            </td>
          </tr>
          <tr>
            <td>お客様電話番号</td>
            <td>
              <%= session[:telephone_number] %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="col py-5 text-center">
      <%= f.submit "注文を確定する", class: "btn btn-lg btn-success" %>
    </div>
  <% end %>
</div>

app/views/customer/orders/index.html.erb
<div class="container my-5">
  <div class="col">
    <h1 class="text-center">
      <i class="fas fa-box-open fa-2x"></i>
      <strong>注文履歴一覧</strong>
    </h1>
  </div>
  <div class="row my-5">
    <div class="col">
      <table class="table table-hover table-bordered">
        <thead class="table-warning">
          <tr>
            <th>注文日</th>
            <th>宛名</th>
            <th>電話番号</th>
            <th>請求金額</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= order.created_at.to_s(:datetime_jp)%>
            </td>
            <td>
              <%= order.delivery_name %>
            </td>
            <td>
              <%= order.delivery_telephone_number %>
            </td>
            <td>
              <%= (order.billing_amount).to_s(:delimited) %> 円
            </td>
            <td class="text-center">
              <%= link_to "注文詳細", order_path(order), class: "btn btn-outline-primary" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container mx-auto pt-5">
  <div class="col">
    <h1 class="text-center">
      <i class="fas fa-pencil-alt fa-2x"></i>
      <strong>注文情報入力</strong>
    </h1>
  </div>
  <%= form_with scope: :session, url: orders_confirm_path, local: true do |f| %>
    <div class="col my-5 mx-auto">
      <h2 class="col text-center mb-4"><strong>支払方法</strong></h2>
      <div class="row d-flex justify-content-center form-group">
        <div class="form-check">
          <%= radio_button_tag :payment_method, :現金, class: "form-check-input" %>
          <label class="form-check-label">現金</label>
        </div>
        <div class="form-check mx-4">
          <%= radio_button_tag :payment_method, :クレジットカード, class: "form-check-input" %>
          <label class="form-check-label">クレジットカード</label>
        </div>
        <div class="form-check">
          <%= radio_button_tag :payment_method, :銀行振込, class: "form-check-input" %>
          <label class="form-check-label">銀行振込</label>
        </div>
      </div>
    </div>
    <h2 class="col text-center mb-4"><strong>お届け先</strong></h2>
    <div class="row pb-5">
      <div class="col-sm-6 col-lg-6 mt-3">
        <div class="form-check mb-2">
          <%= radio_button_tag :delivery, "new_address", class: "form-check-input"%>
          <label class="h5 form-check-label"><strong>本サイトのご利用が初めての方</strong></label>
        </div>
        <h6 class="text-center">
          フォームに各項目を入力してください。
        </h6>
        <div class="card">
          <div class="card-body">
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text">〒</span>
                <%= f.text_field :postal_code, class: "form-control", placeholder: "郵便番号" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-map-marked-alt"></i></span>
                <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-signature"></i></span>
                <%= f.text_field :name, class: "form-control", placeholder: "宛名" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-phone-alt"></i></span>
                <%= f.text_field :telephone_number, class: "form-control", placeholder: "電話番号" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-lg-6 mt-3">
        <div class="form-check mb-2">
          <%= radio_button_tag :delivery, "my_address", class: "form-check-input"%>
          <label class="h5 form-check-label"><strong>配達先の登録が完了している方</strong></label>
        </div>
        <h6 class="text-center">
          セレクトフォームから配達先を選択してください。
        </h6>
        <div class="card">
          <div class="card-body">
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text">〒</span>
                <%= f.select :delivery_postal_code, @deliveries.map{ |delivery| [delivery.postal_code]}, class: "form-control", include_blank: "--選択してください--" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-map-marked-alt"></i></span>
                <%= f.select :delivery_address, @deliveries.map{ |delivery| [delivery.address]}, class: "form-control", include_blank: "--選択してください--" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-signature"></i></span>
                <%= f.select :delivery_name, @deliveries.map{ |delivery| [delivery.name]}, class: "form-control", include_blank: "--選択してください--" %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-text"><i class="fas fa-phone-alt"></i></span>
                <%= f.select :delivery_telephone_number, @deliveries.map{ |delivery| [delivery.telephone_number]}, class: "form-control", include_blank: "--選択してください--" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row my-3 mx-auto">
        <%= f.submit '注文確認画面へ進む', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>  
</div>