config/routes.rb
Rails.application.routes.draw do
  
  
  
  # 顧客側画面・処理のルーティング
  devise_for :members, controllers: {
    sessions: 'customer/sessions',
    passwords: 'customer/passwords',
    registrations: 'customer/registrations',
  }

  scope module: :customer do
    root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    get '/shop' => 'homes#shop'

    get '/pizzas/search' => 'pizzas#search'   # ピザ一覧画面での検索後に表示する、検索結果表示画面
    post '/pizzas/search' => 'pizzas#search'  # ransackによる、ピザ一覧画面での検索処理
    resources :pizzas, only: [:index, :show]

    get '/members/confirm' => 'members#confirm'           # 顧客の退会確認画面
    patch '/members/withdrawal' => 'members#withdrawal'   # 顧客の退会処理(会員ステータスの更新)
    resources :members, only: [:show, :edit, :update]

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all' # カート内商品の全削除
    resources :cart_items, only: [:index, :create, :update, :destroy]

    get '/orders/confirm' => 'orders#confirm'       # 注文情報確認画面
    post '/orders/confirm' => 'orders#confirm'      # 注文情報確認画面の裏処理
    get '/orders/complete' => 'orders#complete'     # 注文完了画面
    resources :orders, only: [:index, :new, :create, :show]

    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
  end

  # <------------------------------------------>

  # 管理者側画面・処理のルーティング
  devise_for :admins, path: 'admin',
                      controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords',
                        registrations: 'admin/registrations',
                      }

  namespace :admin do
    root to: 'homes#top'
    get '/admin' => 'homes#top'
    resources :pizzas
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_pizzas, only: [:update]
  end
  # <------------------------------------------>
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_pizzas
  belongs_to :member

  validates :member_id, :delivery_postal_code, :delivery_address, :delivery_name, :delivery_telephone_number, :billing_amount, :payment_method, presence: true
  validates :delivery_telephone_number, length: { minimum: 10 }
  # enumによる支払方法、注文ステータスの管理
  enum payment_method: { 現金: 0, クレジットカード: 1, 銀行振込: 2 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 配達準備中: 2, 配達準備完了: 3, 配達中: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
  end

  def update
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
    @order.update(order_params)

    # 注文ステータスを「入金確認」にすると、調理ステータスが「調理中」に更新される処理
    if @order.order_status == "入金確認"
      @order_pizzas.update_all(cooking_status: "調理中")
      flash[:success] = "注文ステータスを「入金確認」に、調理ステータスを「調理中」に変更しました！"
      redirect_to admin_order_path(@order)
    # 注文ステータスを「入金待ち」にすると、調理ステータスが「調理不可」に更新される処理
    elsif @order.order_status == "入金待ち"
      @order_pizzas.update_all(cooking_status: "調理不可")
      flash[:success] = "注文ステータスを「入金待ち」に、調理ステータスを「調理不可」に変更しました！"
      redirect_to admin_order_path(@order)
    # 注文ステータスを上記の2項目以外にした場合
    else
      flash[:success] = "注文ステータスを更新しました！"
      redirect_to admin_order_path(@order)
    end
  end

  # 注文データのストロングパラメータ設定
  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_member!

  # 注文情報入力画面
  def new
    @order = Order.new
    @deliveries = Delivery.where(member_id: current_member.id)
  end

  # 注文情報入力画面で入力した内容をsessionで一時保存
  def confirm
    @order = current_member.orders
    @total_price = calculate(current_member)

    session[:payment_method] = params[:payment_method]

    # 「本サイトのご利用が初めての方」を選択した場合の処理
    if params[:delivery] == "new_address"
      session[:postal_code] = params[:session][:postal_code]
      session[:address] = params[:session][:address]
      session[:name] = params[:session][:name]
      session[:telephone_number] = params[:session][:telephone_number]

    # 「マイページにて配達先の登録が完了している方」を選択した場合の処理
    elsif params[:delivery] == "my_address"
      session[:postal_code] =  params[:session][:delivery_postal_code]
      session[:address] = params[:session][:delivery_address]
      session[:name] = params[:session][:delivery_name]
      session[:telephone_number] = params[:session][:delivery_telephone_number]
    end

    # 郵便番号、住所、宛名、電話番号のいずれかが入力されていない場合の処理
    if session[:postal_code] == ""
      flash[:danger] = "郵便番号を入力してください！"
      redirect_to new_order_path
    elsif session[:address] == ""
      flash[:danger] = "配達先住所を入力してください！"
      redirect_to new_order_path
    elsif session[:name] == ""
      flash[:danger] = "宛名を入力してください！"
      redirect_to new_order_path
    elsif session[:telephone_number] == ""
      flash[:danger] = "電話番号を入力してください！"
      redirect_to new_order_path  
    end
    
  end

  def create
    # 注文情報の保存
    @order = Order.new
    @order.member_id = current_member.id
    @order.delivery_postal_code = session[:postal_code]
    @order.delivery_address = session[:address]
    @order.delivery_name = session[:name]
    @order.delivery_telephone_number = session[:telephone_number]
    @order.payment_method = session[:payment_method]
    @order.billing_amount = calculate(current_member)
    @order.order_status = 0
    @order.save

    # 注文商品ごとの詳細データの保存
    current_member.cart_items.each do |cart|
      @order_pizza = OrderPizza.new
      @order_pizza.order_id = @order.id
      @order_pizza.pizza_id = cart.pizza.id
      @order_pizza.price = cart.pizza.price
      @order_pizza.number_of_sheets = cart.number_of_sheets
      @order_pizza.cooking_status = 0
      @order_pizza.save
    end

    # 現在ユーザーのカート内データ、及び支払方法・お届け先データの削除
    current_member.cart_items.destroy_all
    session.delete(:payment_method)
    session.delete(:postal_code)
    session.delete(:address)
    session.delete(:name)
    session.delete(:telephone_number)
    flash[:success] = "注文が完了しました！"
    redirect_to orders_complete_path
  end

  # 注文完了画面
  def complete
  end

  def index
    @orders = Order.where(member_id: current_member.id).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_pizzas = @order.order_pizzas
  end

  # 注文データのストロングパラメータ
  private

  def confirm_params
    params.permit(:payment_method, :postal_code, :address, :name, :telephone_number)
  end

  def calculate(member)
    total_price = 0
    member.cart_items.each do |cart_item|
      total_price += cart_item.number_of_sheets * cart_item.pizza.price
    end
    (total_price * 1.1).floor
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row mb-4">
    <h1><strong>注文履歴詳細</strong></h1>
  </div>
  <div class="row mb-4">
    <div class="col-sm-6 mx-auto">
      <table class="table table-bordered table-hover">
        <tbody>
          <tr>
            <td class="table-dark">
              購入者
            </td>
            <td>
              <%= link_to admin_member_path(@order.member_id) do %>
                <%= @order.member.full_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="table-dark">
              注文日
            </td>
            <td>
              <%= @order.created_at.to_s(:datetime_jp) %>
            </td>
          </tr>
          <tr>
            <td class="table-dark">
              配送先情報
            </td>
            <td>
              〒<%= @order.delivery_postal_code %><br>
              <%= @order.delivery_address %><br>
              <%= @order.delivery_name %>
            </td>
          </tr>
          <tr>
            <td class="table-dark">
              支払方法
            </td>
            <td>
              <%= @order.payment_method %>
            </td>
          </tr>
          <tr>
            <td class="table-dark">注文ステータス</td>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
                <%= f.select :order_status, Order.order_statuses.keys, class: "form-control" %>
                <%= f.submit "更新", class: "btn btn-outline-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-sm-12 mx-auto">
      <table class="table table-hover table-border">
        <thead class="table-dark">
          <tr>
            <td>商品名</td>
            <td>単価(税込)</td>
            <td>枚数</td>
            <td>ピザのサイズ</td>
            <td>小計</td>
            <td>調理ステータス</td>
          </tr>
        </thead>
        <tbody>
          <% @order_pizzas.each do |order_pizza| %>
            <tr>
              <td>
                <%= order_pizza.pizza.pizza_name %>
              </td>
              <td>
                <%= (order_pizza.price * 1.1).floor.to_s(:delimited) %> 円
              </td>
              <td>
                <%= order_pizza.number_of_sheets %> 枚
              </td>
              <td>
                <%= order_pizza.pizza.pizza_size %>
              </td>
              <td>
                <%= ((order_pizza.price * 1.1) * (order_pizza.number_of_sheets)).floor.to_s(:delimited) %> 円
              </td>
              <td>
                <%= form_with model: order_pizza, url: admin_order_pizza_path(order_pizza), method: :patch, local: true do |f| %>
                  <%= f.select :cooking_status, OrderPizza.cooking_statuses.keys, class: "form-control" %>
                  <%= f.submit "更新", class: "btn btn-outline-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-sm-4 mx-auto">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="table-danger">
              <strong>請求金額合計<strong>
            </td>
            <td>
              <strong>
                <%= (@order.billing_amount).floor.to_s(:delimited) %> 円
              </strong>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>